--- # vim: ft=yaml.ansible

- name: Create "{{item.name}}" role
  include_tasks: tasks/create-roles.yaml
  vars:
    name: "{{item.name}}"
    privs: "{{item.privs | default(pve_default_privs)}}"

- name: Create "{{item.name}}" group
  include_tasks:
    file: tasks/create-groups.yaml
  vars:
    name: "{{item.name}}"
    role: "{{item.name}}"
    comment: "{{item.comment | default(item.name + ' service account')}}"

- name: Create user "{{item.name}}"
  include_tasks:
    file: tasks/create-users.yaml
  vars:
    name: "{{item.name}}"
    comment: "{{item.comment | default(item.name + ' service account')}}"
    realm: pve

- name: Create API token for user "{{item.name}}"
  include_tasks:
    file: tasks/create-api-tokens.yaml
  vars:
    name: "{{item.name}}"
    realm: pve
    dest: "{{api_key}}"

